name: Continuous Deployment 

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'The log level of the build script.'
        default: 'info'
        required: true
        type: choice
        options:
          - info
          # info: 'Show logs for info, warning and error'
          # verbose: 'Show logs for verbose, info, warning and error'
          # debug: 'Show logs for debug, verbose, info, warning and error'
          # silly: 'Show logs for all levels'
          - error
          # - error: 'Only show error logs'
          - warn
          # warning: 'Show logs for warning and error'
          # warn: 'Show logs for warning and error'
          # none: 'Disable all logs'
          - silent
          # silent: 'Disable all logs'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - name: scavenger-bingo
            localDir: scavenger-bingo
            serverDir: scavengerbingo

    env:
      LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Check if code has changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'apps/${{ matrix.app.localDir }}/**'
              - 'libraries/components/src/**'

      - name: Build and Deploy App
        if: steps.changes.outputs.src == 'true'
        run: |
          cd apps/${{ matrix.app.localDir }}
          yarn build --l $LOG_LEVEL
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WEBGO_SFTP_HOST }} >> ~/.ssh/known_hosts
          rsync -avzP --delete -e "ssh -p 22 -o StrictHostKeyChecking=no" ./dist/ ${{ secrets.WEBGO_SFTP_USERNAME }}@${{ secrets.WEBGO_SFTP_HOST }}:/home/www/de.absolutholz.arcade/${{ matrix.app.serverDir }}
