name: Build and Deploy Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'minimal | standard | verbose'
        required: true
        default: 'verbose'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [scavenger-bingo, tic-tac-toe, dots-and-boxes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install

      - name: Check if code has changed
        id: check_changes
        run: |
          cd apps/${{ matrix.app }}
          git fetch
          if git diff --quiet HEAD remotes/origin/main; then
            echo "Code has not changed for ${matrix.app}"
            echo "::set-output name=changes::false"
          else
            echo "Code has changed for ${matrix.app}"
            echo "::set-output name=changes::true"
          fi

      - name: Build and Deploy App
        if: steps.check_changes.outputs.changes == 'true'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cd apps/${{ matrix.app }}
          yarn build --prod && rsync -azP --delete ./dist/ deploy@example.com:/var/www/${{ matrix.app }}
