name: Build and Deploy Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'The log level of the build script.'
        default: 'info'
        required: false
        options:
          info: 'Show logs for info, warning and error'
          verbose: 'Show logs for verbose, info, warning and error'
          debug: 'Show logs for debug, verbose, info, warning and error'
          silly: 'Show logs for all levels'
          error: 'Only show error logs'
          warning: 'Show logs for warning and error'
          none: 'Disable all logs'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: scavenger-bingo
            localDir: scavenger-bingo
            serverDir: scavengerbingo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Check if code has changed
        id: check_changes
        run: |
          cd apps/${{ matrix.app.localDir }}
          git fetch
          if git diff --quiet HEAD remotes/origin/main; then
            echo "Code has not changed for ${{ matrix.app.name }}"
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Code has changed for ${{ matrix.app.name }}"
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Build and Deploy App
        if: env.changes == 'true'
        run: |
          cd apps/${{ matrix.app.localDir }}
          yarn build --prod --log-level ${{ github.event.inputs.logLevel }}
          ssh-keyscan ${{ secrets.WEBGO_SFTP_HOST }} >> ~/.ssh/known_hosts
          rsync -azP --delete -e "ssh -p 22 -o StrictHostKeyChecking=no" ./dist/ ${{ secrets.WEBGO_SFTP_USERNAME }}@${{ secrets.WEBGO_SFTP_HOST }}:/home/www/de.absolutholz.arcade/${{ matrix.app.serverDir }}
