name: Build and Deploy Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'The log level of the build script. Possible values are "silent", "error", "warn", "info", "debug", and "trace". Defaults to "info".'
        default: 'info'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [scavenger-bingo]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Check if code has changed
        id: check_changes
        run: |
          cd apps/${{ matrix.app }}
          git fetch
          if git diff --quiet HEAD remotes/origin/main; then
            echo "Code has not changed for ${matrix.app}"
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Code has changed for ${matrix.app}"
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Build and Deploy App
        if: steps.check_changes.outputs.changes == 'true'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cd apps/${{ matrix.app }}
          yarn build --prod --log-level ${{ github.event.inputs.logLevel }} && rsync -azP --delete ./dist/ deploy@example.com:/var/www/${{ matrix.app }}
