name: Release Static Assets via FTP

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'minimal | standard | verbose'
        required: true
        default: 'verbose'

  push:
    branches:
      - main

jobs:
  deploy:
    name: copy assets

    strategy:
      matrix:
        include:
          - local-directory: 'libraries/static-assets'
            target-directory: '/arcade-assets/'
            package-name: '@arcade/static-assets'

    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Check if code has changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '${{ matrix.local-directory }}/**'

      - name: Upload to host via FTP
        if: steps.changes.outputs.src == 'true'
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.WEBGO_SFTP_HOST }}
          port: 21
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          password: ${{ secrets.WEBGO_SFTP_PASSWORD }}
          protocol: ftp
          local-dir: ./${{ matrix.local-directory }}/
          server-dir: /home/www/de.absolutholz.arcade${{ matrix.target-directory }}
          log-level: ${{ github.event.inputs.logLevel }}
          exclude: |
            **/package.json
